name: MSBuild

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  # Path to the solution file relative to the root of the project.
  SOLUTION_FILE_PATH: .

  # Configuration type to build.
  # You can convert this to a build matrix if you need coverage of multiple configuration types.
  # https://docs.github.com/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
  BUILD_CONFIGURATION: Release

permissions:
  contents: read

jobs:
  build:
    runs-on: windows-latest
    strategy:
      # 矩阵配置
      matrix:
        qt_ver: [6.2.4]
        qt_target: [desktop]
        qt_arch: [win64_msvc2019_64]
        # 额外设置msvc_arch
        include:
        - qt_arch: win64_msvc2019_64
          msvc_arch: x64
          qt_path: msvc2019_64

    steps:
    # Cache Qt
    - name: Cache Qt
      id: cacheqt6
      uses: actions/cache@v3.0.10
      with:
        # A list of files, directories, and wildcard patterns to cache and restore
        path: ${{github.workspace}}/Qt/${{matrix.qt_ver}}/${{matrix.qt_path}}
        key: win-qt6
    
    # Print env
    - name: Echo env
      shell: pwsh
      run: |
        echo "${{github.workspace}}"
        echo "${RUNNER_WORKSPACE}"
        echo "${{runner.workspace}}"
    
    # Setup Qt
    - name: Setup Qt
      if: steps.cacheqt6.outputs.cache-hit == 'true'
      shell: pwsh
      env:
        QT_PATH: ${{github.workspace}}/Qt/${{matrix.qt_ver}}/${{matrix.qt_path}}
      run: |
        $qtpath=${env:QT_PATH}
        echo "::set-env name=Qt6_DIR::$qtpath"
        echo "::add-path::$qtpath/bin"
    
    # install Qt
    - name: Install Qt
      if: steps.cacheqt6.outputs.cache-hit != 'true'
      uses: jurplel/install-qt-action@v3
      with:
        aqtversion: '==2.1.*'
        version: ${{ matrix.qt_ver }}
        host: 'windows'
        target: ${{ matrix.qt_target }}
        arch: ${{ matrix.qt_arch }}
        modules: 'qtmultimedia'
        tools: 'tools_cmake tools_ninja'
        setup-python: 'false'
    
    # Pull code
    - uses: actions/checkout@v3

    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v1.0.2

    - name: Build
      working-directory: ${{env.GITHUB_WORKSPACE}}
      env:
        QtToolsPath: ${{github.workspace}}/Qt/${{matrix.qt_ver}}/${{matrix.qt_path}}/bin
        
      run: msbuild /m /p:Configuration=${{env.BUILD_CONFIGURATION}} ${{env.SOLUTION_FILE_PATH}}
